"""nova coluna

Revision ID: 0e57dbfb5c25
Revises: ade1e8e2fae4
Create Date: 2021-05-04 22:47:27.900149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e57dbfb5c25'
down_revision = 'ade1e8e2fae4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamanhos', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('tamanhos')

    # ### end Alembic commands ###
