"""novos intens adicionados

Revision ID: 37a770fe5a05
Revises: c8b8f7bb5ce1
Create Date: 2021-06-12 14:38:14.302108

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37a770fe5a05'
down_revision = 'c8b8f7bb5ce1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
