"""inicial

Revision ID: ade1e8e2fae4
Revises: 
Create Date: 2021-05-04 22:43:42.337484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ade1e8e2fae4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_index('ix_produto_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.create_index('ix_produto_id', ['id'], unique=False)

    # ### end Alembic commands ###
