"""novos intens adicionados

Revision ID: c00ef135f779
Revises: 09a139953d92
Create Date: 2021-07-07 21:36:26.327492

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c00ef135f779'
down_revision = '09a139953d92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('tamanhos')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tamanhos', sa.VARCHAR(), nullable=True))

    # ### end Alembic commands ###
