"""Adicionei pedido

Revision ID: c8b8f7bb5ce1
Revises: 368b28cfd122
Create Date: 2021-05-20 21:59:07.439559

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c8b8f7bb5ce1'
down_revision = '368b28cfd122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
